/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const UserId = IDL.Principal;
export const InvestmentAmount = IDL.Nat;
export const Investment = IDL.Record({
  'end_date' : Time,
  'user_id' : UserId,
  'start_date' : Time,
  'plan_id' : IDL.Nat,
  'amount' : InvestmentAmount,
});
export const TransactionAmount = IDL.Nat;
export const ReferralEarning = IDL.Record({
  'referred_user_id' : UserId,
  'referrer_id' : UserId,
  'level' : IDL.Nat,
  'amount' : TransactionAmount,
  'percentage' : IDL.Nat,
});
export const TransactionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'failed' : IDL.Null,
});
export const TransactionType = IDL.Variant({
  'investment' : IDL.Null,
  'referralCommission' : IDL.Null,
  'deposit' : IDL.Null,
  'withdrawal' : IDL.Null,
});
export const Transaction = IDL.Record({
  'status' : TransactionStatus,
  'transaction_type' : TransactionType,
  'created_at' : Time,
  'user_id' : UserId,
  'amount' : TransactionAmount,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ReferralCode = IDL.Text;
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'referred_by' : IDL.Opt(UserId),
  'email' : IDL.Text,
  'referral_code' : ReferralCode,
});
export const InvestmentPlan = IDL.Record({
  'id' : IDL.Nat,
  'durationDays' : IDL.Nat,
  'name' : IDL.Text,
  'maxInvestment' : IDL.Nat,
  'minInvestment' : IDL.Nat,
  'profitPercentage' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addInvestment' : IDL.Func([Investment], [], []),
  'addReferralEarning' : IDL.Func([ReferralEarning], [], []),
  'addTransaction' : IDL.Func([Transaction], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createNewInvestmentPlan' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'getCallerBalance' : IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
  'getCallerInvestment' : IDL.Func([], [IDL.Opt(Investment)], ['query']),
  'getCallerReferralEarnings' : IDL.Func(
      [],
      [IDL.Vec(ReferralEarning)],
      ['query'],
    ),
  'getCallerTransaction' : IDL.Func([], [IDL.Opt(Transaction)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInvestmentPlans' : IDL.Func([], [IDL.Vec(InvestmentPlan)], ['query']),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setCurrentBalance' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const UserId = IDL.Principal;
  const InvestmentAmount = IDL.Nat;
  const Investment = IDL.Record({
    'end_date' : Time,
    'user_id' : UserId,
    'start_date' : Time,
    'plan_id' : IDL.Nat,
    'amount' : InvestmentAmount,
  });
  const TransactionAmount = IDL.Nat;
  const ReferralEarning = IDL.Record({
    'referred_user_id' : UserId,
    'referrer_id' : UserId,
    'level' : IDL.Nat,
    'amount' : TransactionAmount,
    'percentage' : IDL.Nat,
  });
  const TransactionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'failed' : IDL.Null,
  });
  const TransactionType = IDL.Variant({
    'investment' : IDL.Null,
    'referralCommission' : IDL.Null,
    'deposit' : IDL.Null,
    'withdrawal' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'status' : TransactionStatus,
    'transaction_type' : TransactionType,
    'created_at' : Time,
    'user_id' : UserId,
    'amount' : TransactionAmount,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ReferralCode = IDL.Text;
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'referred_by' : IDL.Opt(UserId),
    'email' : IDL.Text,
    'referral_code' : ReferralCode,
  });
  const InvestmentPlan = IDL.Record({
    'id' : IDL.Nat,
    'durationDays' : IDL.Nat,
    'name' : IDL.Text,
    'maxInvestment' : IDL.Nat,
    'minInvestment' : IDL.Nat,
    'profitPercentage' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addInvestment' : IDL.Func([Investment], [], []),
    'addReferralEarning' : IDL.Func([ReferralEarning], [], []),
    'addTransaction' : IDL.Func([Transaction], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createNewInvestmentPlan' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'getCallerBalance' : IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
    'getCallerInvestment' : IDL.Func([], [IDL.Opt(Investment)], ['query']),
    'getCallerReferralEarnings' : IDL.Func(
        [],
        [IDL.Vec(ReferralEarning)],
        ['query'],
      ),
    'getCallerTransaction' : IDL.Func([], [IDL.Opt(Transaction)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInvestmentPlans' : IDL.Func([], [IDL.Vec(InvestmentPlan)], ['query']),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setCurrentBalance' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };