/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Investment {
  'end_date' : Time,
  'user_id' : UserId,
  'start_date' : Time,
  'plan_id' : bigint,
  'amount' : InvestmentAmount,
}
export type InvestmentAmount = bigint;
export interface InvestmentPlan {
  'id' : bigint,
  'durationDays' : bigint,
  'name' : string,
  'maxInvestment' : bigint,
  'minInvestment' : bigint,
  'profitPercentage' : bigint,
}
export type ReferralCode = string;
export interface ReferralEarning {
  'referred_user_id' : UserId,
  'referrer_id' : UserId,
  'level' : bigint,
  'amount' : TransactionAmount,
  'percentage' : bigint,
}
export type Time = bigint;
export interface Transaction {
  'status' : TransactionStatus,
  'transaction_type' : TransactionType,
  'created_at' : Time,
  'user_id' : UserId,
  'amount' : TransactionAmount,
}
export type TransactionAmount = bigint;
export type TransactionStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'failed' : null };
export type TransactionType = { 'investment' : null } |
  { 'referralCommission' : null } |
  { 'deposit' : null } |
  { 'withdrawal' : null };
export type UserId = Principal;
export interface UserProfile {
  'principal' : Principal,
  'referred_by' : [] | [UserId],
  'email' : string,
  'referral_code' : ReferralCode,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addInvestment' : ActorMethod<[Investment], undefined>,
  'addReferralEarning' : ActorMethod<[ReferralEarning], undefined>,
  'addTransaction' : ActorMethod<[Transaction], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createNewInvestmentPlan' : ActorMethod<
    [string, bigint, bigint, bigint, bigint],
    undefined
  >,
  'getCallerBalance' : ActorMethod<[], [] | [bigint]>,
  'getCallerInvestment' : ActorMethod<[], [] | [Investment]>,
  'getCallerReferralEarnings' : ActorMethod<[], Array<ReferralEarning>>,
  'getCallerTransaction' : ActorMethod<[], [] | [Transaction]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInvestmentPlans' : ActorMethod<[], Array<InvestmentPlan>>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setCurrentBalance' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];